### ISSUE TITLE
This program is blocked by group policy.

### ISSUE THREAD

**Issue by thuanxt** [florentbr/SeleniumBasic#24]
I have installed SeleniumBasic-2.0.5.0.

When run the example code, I encountered a run time error exception at Line 79 in ProcessExt.cs. I think it could not create the process. Please help me to fix this problem.

By the way, I use Window 7 64 bit, Microsoft office 2007.

See the attached image for more information. 
![seleniumbasic_issue](https://cloud.githubusercontent.com/assets/10371931/10273004/691d5d9e-6b53-11e5-956c-20ce39026948.png)

**Comment by florentbr** [comment]
Are you able to launch manually the drivers (iedriver.exe, chromedriver.exe ...) present in %USERPROFILE%/AppData\Local\SeleniumBasic ?

**Comment by thuanxt** [comment]
Hi Florent,

I am not able to launch manually the drivers. My computer has a domain which is set up by the IT department of my company, I wonder whether it relates to this issue. However, I can run SeleniumWrapper but I want to migrate to SeleniumBasic.

Thank you for your good work,
Thuan

**Comment by florentbr** [comment]
Basically the error means that Windows is denying the launch of the webdriver. It seems that you have a "Software Policy Rule" that prevents applications in "%USERPROFILE%" from running. But since you've successfully installed it, the %TEMP% folder doesn't have such policy.

It doesn't make any sense since "%TEMP%" is supposed to be in "%USERPROFILE%\AppData\Local". It would mean that the temp folder has been changed or that there is a specific rule to allow applications in it to run.

Can tell the real path for the temporary and user folder ?
  Run (Win+R) "%TEMP%" to get the temp folder
  Run (Win+R) "%USERPROFILE%" to get the user folder

Could you also list the Software Policy Rules ?
 Run "gpedit.msc"
 Rules are in "Computer Configuration > Windows Settings > Security Settings > Software Restriction Policy >  Additional Rules"
 You can export the list from the action menu.

**Comment by thuanxt** [comment]
Hi Florent,

The real path for %TEMP% and %USERPROFILE% folder are as below:
C:\Users\myusername\AppData\Local\Temp
C:\Users\myusername

However, there is no rule in the Software Policy Rules. The "No Software Restriction Policies Defined" message is shown.

**Comment by florentbr** [comment]
It could be defined somewhere else since you are on a domain controller.
Could you post the general description of the error from the Event Viewer:
 C:\Windows\System32\eventvwr.exe
The event must be under "Windows Logs > Application"
It should tell which rule it breaks.

**Comment by thuanxt** [comment]
Hi Florent,

The description is as below:
Access to C:\Users\<myusername>\AppData\Local\SeleniumBasic\iedriver.exe has been restricted by your Administrator by location with policy rule {4d9792dc-46c4-488e-a4ff-dda61fbca603} placed on path C:\Users\<myusername>\AppData\Local\*\*.exe.

I could not find the location where the rule is placed.

**Comment by florentbr** [comment]
I will add an option to install in program files instead when the setup is executed as "Run as administrator".
As a workaround, you could try to add a local "Unrestricted" rule on "%USERPROFILE%\AppData\Local\SeleniumBasic" in "Software Policy Rules", but there is no guaranty that it will work.

**Comment by florentbr** [comment]
The new release v2.0.6.0 now installs in "C:\Program Files\SeleniumBasic" when the setup is executed  as "Run as administrator".
