### ISSUE TITLE
SessionNotCreatedError

### ISSUE THREAD

**Issue by mhenson1** [florentbr/SeleniumBasic#26]
I installed the latest release of SeleniumBasic on a new machine and when I try running these lines

Set selenium = CreateObject("Selenium.ChromeDriver")
selenium.SetBinary "C:\Program Files (x86)\folder\MyCEFapplication.exe"
selenium.SetCapability "debuggerAddress", "127.0.0.1:38947"
selenium.Start

I get this error
![error](https://cloud.githubusercontent.com/assets/13964333/10344751/12ca93a2-6cf3-11e5-9eb6-7980a510c051.png)

I feel like this has to be some sort of machine setup issue because I have 2 other machines that I've installed it on with no issues. The problem machine is using 64 bit Windows 7.

I was mainly curious if you had seen this issue before or had any info on it. I've done some googling on the errors but I've been unable to turn up anything useful for why it's occurring or how to fix it.

Thanks

**Comment by florentbr** [comment]
I've just tested it on Windows 7 64bits with CEF 3.2494 32bits and couldn't reproduce your issue.
Moreover, you shouldn't use SetBinary while setting the "debuggerAddress" capability since it is for connecting to a CEF browser that is already launched.

To launch and drive CEF:

    Set driver = CreateObject("Selenium.ChromeDriver")
    driver.SetBinary "C:\cef\cefclient.exe"
    driver.AddArgument "url=data:,"
    driver.Get "https://en.wikipedia.org"
    ...
    driver.Quit

To connect to a CEF browser that was launched with a debug port:

    'Use this command line to launch the browser:
    'cefclient.exe -remote-debugging-port=9333 -url=data:,
    
    Set driver = CreateObject("Selenium.ChromeDriver")
    driver.SetCapability "debuggerAddress", "127.0.0.1:9333"
    driver.Get "https://en.wikipedia.org"
    ...
    driver.Quit

Anyway, since you use a customized CEF version, it is probably not compatible with the chrome driver.

**Comment by mhenson1** [comment]
Just in case you were curious I figured out that this was because Java somehow got removed from my machine. After installing the JRE back everything worked fine. Sorry about the trouble.
