### ISSUE TITLE
access to webdriver cababilities especially location of browser binary

### ISSUE THREAD

**Issue by dornech** [florentbr/SeleniumBasic#4]
to use seleniumbasic with portable versions of the browser it is necessary to set the respective capability. it seems that seleniumbasic right now does not allow to provide the embedded webdriver with a non-stanard location of the browser binaries.

**Comment by florentbr** [comment]
It is possible to set the location of the binary through capabilities.
For Firefox:
driver.SetCapability "firefox_binary", "c:\...\firefox.exe"

**Comment by dornech** [comment]
oh, thanks, that's great. however, i wonder if the possible capabilities are described elsewhere. I could not find the identifier "firefox_binary" in the officially documented webdriver capabilities but only a cabability "binary". is there any list available or any mapping rule from seleniumbasic-capability identifiers to the "offical" identifiers ?

furthermore, is it possible to read a capability ? I only found set-methods. however, to enable scripts to run in any environment it would be helpful to check first if the desired browser is available at the webdriver assumed default location and if not, to search at other places (i e search for a portable verison being installed).

**Comment by florentbr** [comment]
> i wonder if the possible capabilities are described elsewhere. I could not find the identifier "firefox_binary"

The "firefox_binary" capability is in the official documentation:
https://code.google.com/p/selenium/wiki/DesiredCapabilities
FYI I've added the SetBinary method in the next release.

> furthermore, is it possible to read a capability ?

No, there is currently no property to list all the available capabilities as it's only possible to list the generic ones and because there are only known once the browser is launched.

> it would be helpful to check first if the desired browser is available at the webdriver assumed default location...

I don't see how it would help as it is not an assumed location. When a browser is installed, its location is written in this registry key:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths
So if this key is missing, the browser is not available or the user has a portable version and therefore the location is unknown.
And even with an assumed the location, you could easily check it using a simple condition:

    Dim driver As New FirefoxDriver
    If Dir("c:\portable\firefox.exe") <> Empty Then
        driver.SetCapability "firefox_binary", "c:\portable\firefox.exe"
    End If
    driver.Get "http://www..."

**Comment by dornech** [comment]
thanks for the reply. 

I am afraid I got a little bit confused by different sources regarding the binary capability.

hint regarding registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths is good. thanks for this, this will help me.

**Comment by dornech** [comment]
I wonder if you would comment on setting the binary capability for Chrome. It works fine for Firefox but I do not get the binary capability running for Chrome.

**Comment by florentbr** [comment]
The SetBinary method is now available since release v2.0.3.0:

    Dim driver As New ChromeDriver
    driver.SetBinary "C:\...\cefclient.exe"
    driver.AddArgument "url=data:,"
    driver.Get "https://www.google.co.uk"
    driver.Quit

    Dim driver As New FirefoxDriver
    driver.SetBinary "C:\...\light.exe"
    driver.Get "https://www.google.co.uk"
    driver.Quit

**Comment by dornech** [comment]
solved with the update. again, thanks for the great work.
