### ISSUE TITLE
Calling the Quit method on a ChromeDriver object makes the Escape key stop working

### ISSUE THREAD

**Issue by jhertel** [florentbr/SeleniumBasic#43]
Running this small snippet of code in Excel 2007 on Windows 7 makes the Escape (Esc) key not work in Windows programs at all, until you exit Excel completely:

```vb
Public Sub MakeEscapeNotWork()
    Dim driver As New ChromeDriver
    driver.Quit
End Sub
```

Escape works fine just before the driver.Quite statement, but stops working right after it has been called.

As I use the Escape key a lot (especially to close dialogs and menus), this bug is of course rather annoying. 

But until the bug has been fixed, I will just avoid using .Quit and hope I can do without it.

**Comment by dornech** [comment]
Thank you for sharing your observation. I recently noticed that my ESC-key is not working from time to time. So far I did not link this to Selenium / SeleniumBasic but I can not at all outrule that the problem ooccurs since I am working with SeleniumBasic. Actually I think it is more likely than not.
