### ISSUE TITLE
How to make POST request using PhantomJS driver

### ISSUE THREAD

**Issue by zaka786khan** [florentbr/SeleniumBasic#46]
Hi Dear Florentbr!

I have a little question about how to make a POST request submitting with some variables and values without HTML forms. For example I want to start a POST request directly instead of opening first login page, filling form values and then submit form. 

How to submit values with POST request to a page. Thanks.

**Comment by dornech** [comment]
I wonder why you think you need to use a webdriver for sending a POST request.
Respective object (HTTPrequest)  ist contained in the WinHTTP library and can be used without any webdriver.
For investigating the necessary parameters I recommend to use Fiddler.

**Comment by zaka786khan** [comment]
dornech! making a POST request is shorter way to submit form or skip login form. Sometimes, It is requirement to do POST request for example a website is offering API which need to be POST request to be made to let work. API require POST requests for working and returns JSON result. 

Testing such websites/API's one must have to  make a POST request. So, please help me making such POST requests through SeleniumBasic with Phantomjs Driver. Thanks alot

**Comment by dornech** [comment]
zaka786khan,
thanks for your explanation but I I think I am well experienced with HTTP requests and I am able to use it, especially for web scraping, this is the main thing I use Selenium for.
However, I still do not understand why you want to do a post request via Selenium. Selenium is more a replacement for the library MSHTML to remotely control browsers beside the IE. And a HTTP request (actually POST is a specifically parameterized HTTP request) is defined in the Win HTTP library. 
To submit POST requests, it is necessary to understand the parameter semantics i e how to build the body and to set call parameters. The semantics are determined by the web page, not any external tool. For that reason I recommended to use Fiddler or a similar tool to analyze the request structure in order to be able to rebuild proper POST requests for your needs.
I guess you encounter a problem I had when starting with WinHTTP POST requests: when retrieving data from websites subject to a log in, it is necessary to pass on parameters like a sessionID or authorization parameters which are typically contained in cookies. To overcome this you do the login via Selenium to have a session opened and authorized. You may then extract the required cookies for your POST using the HTTP request object from WinHTTP. However, as mentioned above, this requires some more or less painful analysis with Fiddler to succeed in defining the right parameterization of the HTTP request.

**Comment by florentbr** [comment]
There's no added value in using Selenium or PhantomJS if you are willing to use raw requests.
Here is an example to send a simple HTTP request in VBA:
https://msdn.microsoft.com/en-us/library/ms535874(v=vs.85).aspx
```vbs
Sub Test_Native_HttpRequest()
  Set http = CreateObject("MSXML2.XMLHTTP")
  http.Open "GET", "https://vortex.data.microsoft.com/collect/v1", False
  http.SetRequestHeader "User-Agent", "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36"
  http.SetRequestHeader "Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
  http.Send ""
  Debug.Print http.responseText
End Sub
```

But since you asked, here is an example with Selenium with a Javascript call:
https://developer.mozilla.org/fr/docs/Web/API/XMLHttpRequest
```vbs
Sub Test_Selenium_HttpRequest()
  Dim drv As New Selenium.PhantomJSDriver
  drv.Get "https://vortex.data.microsoft.com"
  
  Const JS_HTTP_GET As String = _
    "var url = arguments[0];" & _
    "var r = new XMLHttpRequest();" & _
    "r.open('GET', url, false);" & _
    "r.send(null);" & _
    "return JSON.parse(r.responseText);"
    
  Set result = drv.ExecuteScript(JS_HTTP_GET, "https://vortex.data.microsoft.com/collect/v1")
  
  drv.Quit
End Sub
```
