### ISSUE TITLE
Run-time error '429': ActiveX component can't create object

### ISSUE THREAD

**Issue by pmehrsam** [florentbr/SeleniumBasic#6]
<b>Excel Setup</b>
I have the following setup in my Excel
Tools -> References -> SeleniumWrapper Type Library

<b>Excel VBA</b>
Here is the Excel VBA code I'm running:
Option Explicit

Public Sub SeleniumTest()
Dim driver As New WebDriver
Set driver = CreateObject("WebDriver")  <b><- I get the  Run-time error '429': ActiveX component can't create object error on this line</b>
driver.Start "IE", "https://www.google.com/"

End Sub

<b>Troubleshooting Comments</b>
I first "repaired" my installation of Excel from control panel.  Then I un-installed and re-installed Excel from control panel.  I'm still getting the error.

I don't have the admin rights or experience to manually edit my registry and DLL files.  Is there a way to fix this without getting too low level?

Thanks, Paul

**Comment by florentbr** [comment]
First, make sure you have properly uninstalled the last version of SeleniumWrapper
and that you have the last version of SeleniumBasic Installed:
https://github.com/florentbr/SeleniumBasic/releases

> I have the following setup in my Excel
> Tools -> References -> SeleniumWrapper Type Library

The new reference in VBA is:
Tools -> References -> Selenium Type Library


> ActiveX component can't create object

The correct syntax for VBA is:

    Dim driver As New Selenium.FirefoxDriver
    driver.Get "https://www.google.co.uk"
    ...
    driver.Quit

or

    Dim driver As New Selenium.WebDriver
    driver.Start "firefox", "https://www.google.co.uk"
    driver.Get "/"
    ...
    driver.Quit

See, the provided workbook for more examples:
Program > Examples > Excel >Selenium.xlsm
or:
https://github.com/florentbr/SeleniumBasic/raw/master/Examples/Excel/Selenium.xlsm


> I don't have the admin rights or experience to manually edit my registry ...

Admin rights are no longer required since the migration.
