### ISSUE TITLE
Edge driver fails to register session

### ISSUE THREAD

**Issue by dexterial** [florentbr/SeleniumBasic#79]
i get this error in VBA excel, although the Edge browser actually starts

"NoSuchDriverError
A session is either terminated or not started"

**Comment by florentbr** [comment]
Could you provide a failing example and tell at which step exactly if is failing?

**Comment by dexterial** [comment]
Edge browser starts, but the driver returns the session error in attached screenshot, excel 2013 32 bit/windows 10 64 bit and see pic for the Edge version. The code did work couple of weeks ago... so i am guessing some edge update is the culprit.

![image](https://cloud.githubusercontent.com/assets/6522692/13196462/9fe934f0-d7ce-11e5-9659-a6190637d56a.png)


![image](https://cloud.githubusercontent.com/assets/6522692/13196455/4e1f5294-d7ce-11e5-8295-139eed010c2a.png)

**Comment by florentbr** [comment]
I couldn't reproduce your issue on a fully updated Windows 10 with all the security features disabled.
Your workbook may have an obsolete reference to Selenium, so try to remove the reference and add again.
If it doesn't solve your issue, it's probably due to a third application blocking the communication between the driver and the browser.
